name: Codex Work Request
description: Request Codex-driven implementation, review, or refinement with clear acceptance criteria.
title: "[codex] "
labels:
  - codex:triage
body:
  - type: markdown
    attributes:
      value: |
        Use this form for Codex intake.
        Codex will decide whether it can execute autonomously or needs maintainer action first.

  - type: dropdown
    id: request_kind
    attributes:
      label: Request Kind
      options:
        - feature
        - bug
        - chore
        - docs
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - p0
        - p1
        - p2
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - web
        - api
        - infra
        - spec
        - ci
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Goal
      description: What should be solved and why now?
      placeholder: Current pain and desired outcome.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should users/developers observe after completion?
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope (In / Out)
      description: Define in-scope and explicitly out-of-scope items.
      placeholder: |
        In:
        - ...
        Out:
        - ...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Testable checklist. Each item should be verifiable.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints / Risks
      description: Security, compliance, access limits, env requirements, deadlines.
      placeholder: Credentials, external services, data migration, approvals, etc.
    validations:
      required: false

  - type: dropdown
    id: autonomous_possible
    attributes:
      label: Can Codex execute end-to-end without human work?
      options:
        - "yes"
        - "no"
        - "unsure"
    validations:
      required: true

  - type: textarea
    id: required_human_action
    attributes:
      label: Required Human Action (if no/unsure)
      description: Exact maintainer actions Codex cannot perform.
      placeholder: Access grant, business decision, manual verification, external approval, etc.
    validations:
      required: false

  - type: checkboxes
    id: quality_gate
    attributes:
      label: Quality Gate
      options:
        - label: I provided enough detail for spec -> plan -> tasks derivation.
          required: true
        - label: I understand Codex may mark this as blocked and request maintainer action.
          required: true
