export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_SESSION_REQUIRED: "AUTH_SESSION_REQUIRED",
  AUTH_CSRF_INVALID: "AUTH_CSRF_INVALID",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_ACCOUNT_DEACTIVATED: "USER_ACCOUNT_DEACTIVATED",
  AUTH_REQUEST_COOLDOWN: "AUTH_REQUEST_COOLDOWN",
  CHANNEL_CREATE_LIMIT_REACHED: "CHANNEL_CREATE_LIMIT_REACHED",
  CHANNEL_JOIN_LIMIT_REACHED: "CHANNEL_JOIN_LIMIT_REACHED",
  CHANNEL_NOT_FOUND: "CHANNEL_NOT_FOUND",
  CHANNEL_PERMISSION_DENIED: "CHANNEL_PERMISSION_DENIED",
  CHANNEL_ALREADY_MEMBER: "CHANNEL_ALREADY_MEMBER",
  CHANNEL_JOIN_REQUEST_PENDING: "CHANNEL_JOIN_REQUEST_PENDING",
  CHANNEL_JOIN_REQUEST_NOT_FOUND: "CHANNEL_JOIN_REQUEST_NOT_FOUND",
  CHANNEL_OWNER_TRANSFER_REQUIRED: "CHANNEL_OWNER_TRANSFER_REQUIRED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
