export const SUCCESS_CODES = {
  AUTH_SIGNUP_VERIFICATION_SENT: "AUTH_SIGNUP_VERIFICATION_SENT",
  AUTH_EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  AUTH_VERIFICATION_RESEND_ACCEPTED: "AUTH_VERIFICATION_RESEND_ACCEPTED",
  AUTH_PASSWORD_RESET_LINK_SENT: "AUTH_PASSWORD_RESET_LINK_SENT",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  CHANNEL_JOIN_REQUEST_CREATED: "CHANNEL_JOIN_REQUEST_CREATED",
  CHANNEL_JOIN_REQUEST_APPROVED: "CHANNEL_JOIN_REQUEST_APPROVED",
  CHANNEL_JOIN_REQUEST_REJECTED: "CHANNEL_JOIN_REQUEST_REJECTED",
  CHANNEL_MANAGER_ASSIGNED: "CHANNEL_MANAGER_ASSIGNED",
  CHANNEL_MANAGER_REMOVED: "CHANNEL_MANAGER_REMOVED",
  CHANNEL_MEMBER_KICKED: "CHANNEL_MEMBER_KICKED",
  CHANNEL_QUIT: "CHANNEL_QUIT",
  CHANNEL_OWNERSHIP_TRANSFERRED: "CHANNEL_OWNERSHIP_TRANSFERRED",
  CHANNEL_OWNED_ORDER_SAVED: "CHANNEL_OWNED_ORDER_SAVED",
  CHANNEL_MY_ORDER_SAVED: "CHANNEL_MY_ORDER_SAVED",
  CHANNEL_POST_DELETED: "CHANNEL_POST_DELETED",
  USER_ACCOUNT_DEACTIVATED: "USER_ACCOUNT_DEACTIVATED",
  USER_DELETION_SCHEDULED: "USER_DELETION_SCHEDULED",
  USER_DELETION_CANCELED: "USER_DELETION_CANCELED"
} as const;

export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES];
